export const countryCodes: {code:string, prefix:string, label:string}[] = [
  { code: "AF", prefix: "+93", label: "Afghanistan" },
  { code: "AL", prefix: "+355", label: "Albania" },
  { code: "DZ", prefix: "+213", label: "Algeria" },
  { code: "AS", prefix: "+1-684", label: "American Samoa" },
  { code: "AD", prefix: "+376", label: "Andorra" },
  { code: "AO", prefix: "+244", label: "Angola" },
  { code: "AI", prefix: "+1-264", label: "Anguilla" },
  { code: "AQ", prefix: "+672", label: "Antarctica" },
  { code: "AG", prefix: "+1-268", label: "Antigua and Barbuda" },
  { code: "AR", prefix: "+54", label: "Argentina" },
  { code: "AM", prefix: "+374", label: "Armenia" },
  { code: "AW", prefix: "+297", label: "Aruba" },
  { code: "AU", prefix: "+61", label: "Australia" },
  { code: "AT", prefix: "+43", label: "Austria" },
  { code: "AZ", prefix: "+994", label: "Azerbaijan" },

  { code: "BS", prefix: "+1-242", label: "Bahamas" },
  { code: "BH", prefix: "+973", label: "Bahrain" },
  { code: "BD", prefix: "+880", label: "Bangladesh" },
  { code: "BB", prefix: "+1-246", label: "Barbados" },
  { code: "BY", prefix: "+375", label: "Belarus" },
  { code: "BE", prefix: "+32", label: "Belgium" },
  { code: "BZ", prefix: "+501", label: "Belize" },
  { code: "BJ", prefix: "+229", label: "Benin" },
  { code: "BM", prefix: "+1-441", label: "Bermuda" },
  { code: "BT", prefix: "+975", label: "Bhutan" },
  { code: "BO", prefix: "+591", label: "Bolivia" },
  { code: "BA", prefix: "+387", label: "Bosnia and Herzegovina" },
  { code: "BW", prefix: "+267", label: "Botswana" },
  { code: "BR", prefix: "+55", label: "Brazil" },
  { code: "IO", prefix: "+246", label: "British Indian Ocean Territory" },
  { code: "VG", prefix: "+1-284", label: "British Virgin Islands" },
  { code: "BN", prefix: "+673", label: "Brunei" },
  { code: "BG", prefix: "+359", label: "Bulgaria" },
  { code: "BF", prefix: "+226", label: "Burkina Faso" },
  { code: "BI", prefix: "+257", label: "Burundi" },

  { code: "KH", prefix: "+855", label: "Cambodia" },
  { code: "CM", prefix: "+237", label: "Cameroon" },
  { code: "CA", prefix: "+1", label: "Canada" },
  { code: "CV", prefix: "+238", label: "Cape Verde" },
  { code: "KY", prefix: "+1-345", label: "Cayman Islands" },
  { code: "CF", prefix: "+236", label: "Central African Republic" },
  { code: "TD", prefix: "+235", label: "Chad" },
  { code: "CL", prefix: "+56", label: "Chile" },
  { code: "CN", prefix: "+86", label: "China" },
  { code: "CX", prefix: "+61", label: "Christmas Island" },
  { code: "CC", prefix: "+61", label: "Cocos (Keeling) Islands" },
  { code: "CO", prefix: "+57", label: "Colombia" },
  { code: "KM", prefix: "+269", label: "Comoros" },
  { code: "CK", prefix: "+682", label: "Cook Islands" },
  { code: "CR", prefix: "+506", label: "Costa Rica" },
  { code: "HR", prefix: "+385", label: "Croatia" },
  { code: "CU", prefix: "+53", label: "Cuba" },
  { code: "CW", prefix: "+599", label: "Curaçao" },
  { code: "CY", prefix: "+357", label: "Cyprus" },
  { code: "CZ", prefix: "+420", label: "Czech Republic" },

  { code: "CD", prefix: "+243", label: "Democratic Republic of the Congo" },
  { code: "DK", prefix: "+45", label: "Denmark" },
  { code: "DJ", prefix: "+253", label: "Djibouti" },
  { code: "DM", prefix: "+1-767", label: "Dominica" },
  { code: "DO", prefix: "+1-809", label: "Dominican Republic" },

  { code: "TL", prefix: "+670", label: "Timor-Leste" },
  { code: "EC", prefix: "+593", label: "Ecuador" },
  { code: "EG", prefix: "+20", label: "Egypt" },
  { code: "SV", prefix: "+503", label: "El Salvador" },
  { code: "GQ", prefix: "+240", label: "Equatorial Guinea" },
  { code: "ER", prefix: "+291", label: "Eritrea" },
  { code: "EE", prefix: "+372", label: "Estonia" },
  { code: "SZ", prefix: "+268", label: "Eswatini" },
  { code: "ET", prefix: "+251", label: "Ethiopia" },

  { code: "FK", prefix: "+500", label: "Falkland Islands" },
  { code: "FO", prefix: "+298", label: "Faroe Islands" },
  { code: "FJ", prefix: "+679", label: "Fiji" },
  { code: "FI", prefix: "+358", label: "Finland" },
  { code: "FR", prefix: "+33", label: "France" },
  { code: "GF", prefix: "+594", label: "French Guiana" },
  { code: "PF", prefix: "+689", label: "French Polynesia" },
  { code: "TF", prefix: "+262", label: "French Southern Territories" },

  { code: "GA", prefix: "+241", label: "Gabon" },
  { code: "GM", prefix: "+220", label: "Gambia" },
  { code: "GE", prefix: "+995", label: "Georgia" },
  { code: "DE", prefix: "+49", label: "Germany" },
  { code: "GH", prefix: "+233", label: "Ghana" },
  { code: "GI", prefix: "+350", label: "Gibraltar" },
  { code: "GR", prefix: "+30", label: "Greece" },
  { code: "GL", prefix: "+299", label: "Greenland" },
  { code: "GD", prefix: "+1-473", label: "Grenada" },
  { code: "GP", prefix: "+590", label: "Guadeloupe" },
  { code: "GU", prefix: "+1-671", label: "Guam" },
  { code: "GT", prefix: "+502", label: "Guatemala" },
  { code: "GG", prefix: "+44", label: "Guernsey" },
  { code: "GN", prefix: "+224", label: "Guinea" },
  { code: "GW", prefix: "+245", label: "Guinea-Bissau" },
  { code: "GY", prefix: "+592", label: "Guyana" },

  { code: "HT", prefix: "+509", label: "Haiti" },
  { code: "HM", prefix: "+672", label: "Heard Island and McDonald Islands" },
  { code: "VA", prefix: "+379", label: "Vatican City" },
  { code: "HN", prefix: "+504", label: "Honduras" },
  { code: "HK", prefix: "+852", label: "Hong Kong" },
  { code: "HU", prefix: "+36", label: "Hungary" },

  { code: "IS", prefix: "+354", label: "Iceland" },
  { code: "IN", prefix: "+91", label: "India" },
  { code: "ID", prefix: "+62", label: "Indonesia" },
  { code: "IR", prefix: "+98", label: "Iran" },
  { code: "IQ", prefix: "+964", label: "Iraq" },
  { code: "IE", prefix: "+353", label: "Ireland" },
  { code: "IM", prefix: "+44", label: "Isle of Man" },
  { code: "IL", prefix: "+972", label: "Israel" },
  { code: "IT", prefix: "+39", label: "Italy" },

  { code: "JM", prefix: "+1-876", label: "Jamaica" },
  { code: "JP", prefix: "+81", label: "Japan" },
  { code: "JE", prefix: "+44", label: "Jersey" },
  { code: "JO", prefix: "+962", label: "Jordan" },

  { code: "KZ", prefix: "+7", label: "Kazakhstan" },
  { code: "KE", prefix: "+254", label: "Kenya" },
  { code: "KI", prefix: "+686", label: "Kiribati" },
  // Note: Kosovo does not have an official ISO 3166‑1 code.
  { code: "XK", prefix: "+383", label: "Kosovo" },
  { code: "KW", prefix: "+965", label: "Kuwait" },
  { code: "KG", prefix: "+996", label: "Kyrgyzstan" },

  { code: "LA", prefix: "+856", label: "Laos" },
  { code: "LV", prefix: "+371", label: "Latvia" },
  { code: "LB", prefix: "+961", label: "Lebanon" },
  { code: "LS", prefix: "+266", label: "Lesotho" },
  { code: "LR", prefix: "+231", label: "Liberia" },
  { code: "LY", prefix: "+218", label: "Libya" },
  { code: "LI", prefix: "+423", label: "Liechtenstein" },
  { code: "LT", prefix: "+370", label: "Lithuania" },
  { code: "LU", prefix: "+352", label: "Luxembourg" },

  { code: "MO", prefix: "+853", label: "Macau" },
  { code: "MG", prefix: "+261", label: "Madagascar" },
  { code: "MW", prefix: "+265", label: "Malawi" },
  { code: "MY", prefix: "+60", label: "Malaysia" },
  { code: "MV", prefix: "+960", label: "Maldives" },
  { code: "ML", prefix: "+223", label: "Mali" },
  { code: "MT", prefix: "+356", label: "Malta" },
  { code: "MH", prefix: "+692", label: "Marshall Islands" },
  { code: "MQ", prefix: "+596", label: "Martinique" },
  { code: "MR", prefix: "+222", label: "Mauritania" },
  { code: "MU", prefix: "+230", label: "Mauritius" },
  { code: "YT", prefix: "+262", label: "Mayotte" },
  { code: "MX", prefix: "+52", label: "Mexico" },
  { code: "FM", prefix: "+691", label: "Micronesia" },
  { code: "MD", prefix: "+373", label: "Moldova" },
  { code: "MC", prefix: "+377", label: "Monaco" },
  { code: "MN", prefix: "+976", label: "Mongolia" },
  { code: "ME", prefix: "+382", label: "Montenegro" },
  { code: "MS", prefix: "+1-664", label: "Montserrat" },
  { code: "MA", prefix: "+212", label: "Morocco" },
  { code: "MZ", prefix: "+258", label: "Mozambique" },
  { code: "MM", prefix: "+95", label: "Myanmar" },

  { code: "NA", prefix: "+264", label: "Namibia" },
  { code: "NR", prefix: "+674", label: "Nauru" },
  { code: "NP", prefix: "+977", label: "Nepal" },
  { code: "NL", prefix: "+31", label: "Netherlands" },
  { code: "NC", prefix: "+687", label: "New Caledonia" },
  { code: "NZ", prefix: "+64", label: "New Zealand" },
  { code: "NI", prefix: "+505", label: "Nicaragua" },
  { code: "NE", prefix: "+227", label: "Niger" },
  { code: "NG", prefix: "+234", label: "Nigeria" },
  { code: "NU", prefix: "+683", label: "Niue" },
  { code: "NF", prefix: "+672", label: "Norfolk Island" },
  { code: "KP", prefix: "+850", label: "North Korea" },
  { code: "MK", prefix: "+389", label: "North Macedonia" },
  { code: "MP", prefix: "+1-670", label: "Northern Mariana Islands" },
  { code: "NO", prefix: "+47", label: "Norway" },

  { code: "OM", prefix: "+968", label: "Oman" },
  { code: "PK", prefix: "+92", label: "Pakistan" },
  { code: "PW", prefix: "+680", label: "Palau" },
  { code: "PS", prefix: "+970", label: "Palestine" },
  { code: "PA", prefix: "+507", label: "Panama" },
  { code: "PG", prefix: "+675", label: "Papua New Guinea" },
  { code: "PY", prefix: "+595", label: "Paraguay" },
  { code: "PE", prefix: "+51", label: "Peru" },
  { code: "PH", prefix: "+63", label: "Philippines" },
  { code: "PN", prefix: "+64", label: "Pitcairn Islands" },
  { code: "PL", prefix: "+48", label: "Poland" },
  { code: "PT", prefix: "+351", label: "Portugal" },
  { code: "PR", prefix: "+1", label: "Puerto Rico" },

  { code: "QA", prefix: "+974", label: "Qatar" },
  { code: "RO", prefix: "+40", label: "Romania" },
  { code: "RU", prefix: "+7", label: "Russia" },
  { code: "RW", prefix: "+250", label: "Rwanda" },

  { code: "BL", prefix: "+590", label: "Saint Barthélemy" },
  { code: "SH", prefix: "+290", label: "Saint Helena" },
  { code: "KN", prefix: "+1-869", label: "Saint Kitts and Nevis" },
  { code: "LC", prefix: "+1-758", label: "Saint Lucia" },
  { code: "MF", prefix: "+590", label: "Saint Martin" },
  { code: "PM", prefix: "+508", label: "Saint Pierre and Miquelon" },
  { code: "VC", prefix: "+1-784", label: "Saint Vincent and the Grenadines" },
  { code: "WS", prefix: "+685", label: "Samoa" },
  { code: "SM", prefix: "+378", label: "San Marino" },
  { code: "ST", prefix: "+239", label: "São Tomé and Príncipe" },
  { code: "SA", prefix: "+966", label: "Saudi Arabia" },
  { code: "SN", prefix: "+221", label: "Senegal" },
  { code: "RS", prefix: "+381", label: "Serbia" },
  { code: "SC", prefix: "+248", label: "Seychelles" },
  { code: "SL", prefix: "+232", label: "Sierra Leone" },
  { code: "SG", prefix: "+65", label: "Singapore" },
  { code: "SX", prefix: "+1-721", label: "Sint Maarten" },
  { code: "SK", prefix: "+421", label: "Slovakia" },
  { code: "SI", prefix: "+386", label: "Slovenia" },
  { code: "SB", prefix: "+677", label: "Solomon Islands" },
  { code: "SO", prefix: "+252", label: "Somalia" },
  { code: "ZA", prefix: "+27", label: "South Africa" },
  { code: "GS", prefix: "+500", label: "South Georgia and the South Sandwich Islands" },
  { code: "KR", prefix: "+82", label: "South Korea" },
  { code: "SS", prefix: "+211", label: "South Sudan" },
  { code: "ES", prefix: "+34", label: "Spain" },
  { code: "LK", prefix: "+94", label: "Sri Lanka" },
  { code: "SD", prefix: "+249", label: "Sudan" },
  { code: "SR", prefix: "+597", label: "Suriname" },
  { code: "SJ", prefix: "+47", label: "Svalbard and Jan Mayen" },
  { code: "SE", prefix: "+46", label: "Sweden" },
  { code: "CH", prefix: "+41", label: "Switzerland" },
  { code: "SY", prefix: "+963", label: "Syria" },

  { code: "TW", prefix: "+886", label: "Taiwan" },
  { code: "TJ", prefix: "+992", label: "Tajikistan" },
  { code: "TZ", prefix: "+255", label: "Tanzania" },
  { code: "TH", prefix: "+66", label: "Thailand" },
  { code: "TG", prefix: "+228", label: "Togo" },
  { code: "TK", prefix: "+690", label: "Tokelau" },
  { code: "TO", prefix: "+676", label: "Tonga" },
  { code: "TT", prefix: "+1-868", label: "Trinidad and Tobago" },
  { code: "TN", prefix: "+216", label: "Tunisia" },
  { code: "TR", prefix: "+90", label: "Turkey" },
  { code: "TM", prefix: "+993", label: "Turkmenistan" },
  { code: "TC", prefix: "+1-649", label: "Turks and Caicos Islands" },
  { code: "TV", prefix: "+688", label: "Tuvalu" },

  { code: "UG", prefix: "+256", label: "Uganda" },
  { code: "UA", prefix: "+380", label: "Ukraine" },
  { code: "AE", prefix: "+971", label: "United Arab Emirates" },
  // Many applications use "UK" for United Kingdom even though the official ISO alpha‑2 is "GB"
  { code: "UK", prefix: "+44", label: "United Kingdom" },
  { code: "US", prefix: "+1", label: "United States" },
  { code: "VI", prefix: "+1-340", label: "United States Virgin Islands" },
  { code: "UY", prefix: "+598", label: "Uruguay" },
  { code: "UZ", prefix: "+998", label: "Uzbekistan" },

  { code: "VU", prefix: "+678", label: "Vanuatu" },
  { code: "VE", prefix: "+58", label: "Venezuela" },
  { code: "VN", prefix: "+84", label: "Vietnam" },

  { code: "WF", prefix: "+681", label: "Wallis and Futuna" },
  { code: "EH", prefix: "+212", label: "Western Sahara" },
  { code: "YE", prefix: "+967", label: "Yemen" },
  { code: "ZM", prefix: "+260", label: "Zambia" },
  { code: "ZW", prefix: "+263", label: "Zimbabwe" }
];
